# Generated by Django 4.2.7 on 2023-11-19 09:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.bankaccount'),
        ),
        migrations.AddField(
            model_name='profile',
            name='credit_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.creditcard'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10df4278-d4bf-4566-ac5d-9bf91a351327'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='unsigned_fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='id',
            field=models.UUIDField(default=uuid.UUID('75375fab-3bd5-4e8b-a8a7-0933912f7ec4'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6933183a-4c17-41e7-bc99-236417ff7108'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Banking',
        ),
    ]
