# Generated by Django 4.2.7 on 2023-11-19 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bank_account_profile_credit_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bb7751cb-8246-4b8f-9f14-4e0db06c5826'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dfc22082-5714-4a9a-b79b-12116b44c407'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6b1c16fe-0132-4a60-80ae-d36bd47809b9'), primary_key=True, serialize=False),
        ),
    ]
