# Generated by Django 4.2.7 on 2023-11-22 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_bankaccount_id_alter_creditcard_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='credit_card',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('16e01601-1e07-4dad-9f80-0632bbea2694'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='id',
            field=models.UUIDField(default=uuid.UUID('40c7f610-dd6a-4cd3-97c2-40d9724f0c3c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a4c11d76-61bb-439f-b89f-7e578c9a7a5a'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserBankRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.bankaccount')),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.creditcard')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
