# Generated by Django 4.2.7 on 2023-11-22 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('015f1c69-77c9-464d-8e8e-84c34d72c545'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6455c745-dd11-4e05-a9e6-f25ed0a03786'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fd306e22-a8fb-4ca4-97c4-c7057239a63d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userbankrelation',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
