# Generated by Django 4.2.7 on 2023-11-23 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('716b1a48-7d5b-4bec-a977-ee76f29814e7'), primary_key=True, serialize=False)),
                ('thumbnail', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('remain_quantity', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b96bda0b-7e97-42f3-a54b-f692abd62ae2'), primary_key=True, serialize=False)),
                ('thumbnails', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('attribute', models.JSONField()),
                ('description', models.TextField(default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a97f40a1-773e-40e7-9db0-102dcb438f5a'), primary_key=True, serialize=False)),
                ('star', models.IntegerField(default=5)),
                ('like', models.IntegerField(default=0)),
                ('attachment', models.TextField(default='')),
                ('message', models.TextField(default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variation')),
            ],
        ),
    ]
