# Generated by Django 4.2.7 on 2023-11-14 14:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.UUIDField(default=uuid.UUID('51f7ec1a-0f50-4463-9fc4-0645514d1bd1'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2ca938f4-daaf-47c2-b2b3-dda4f40e2d57'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('358efafe-8122-4aa4-a0c6-a59c68701cb6'), primary_key=True, serialize=False),
        ),
    ]
