# Generated by Django 4.2.7 on 2023-12-01 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('products', '0004_variation_origin_price_variation_retail_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default='05b11b5c-3de6-4b82-87b2-19ac10ba096f', on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
            preserve_default=False,
        ),
    ]
